os: linux
dist: bionic
language: shell
services:
  - docker
branches:
  only:
    - master
install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - travis_retry sh build.sh